version: '3.7'

services:
  mongodb:
    image: mongo:4.2.2
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - ./mongodata:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    restart: always
