ServiceType: private
AllowedRegions:
- ap-southeast-1
ArtifactSourceType: DockerCompose
RepoName: JJGGu/mongodb
DockerComposeEnvPath: .env.example
RegionId: cn-hangzhou
CustomParameters:
- NoEcho: false
  Type: String
  AllowedPattern: ''
  Label: MONGO_INITDB_ROOT_USERNAME
  ConstraintDescription: ''
  Name: MONGO_INITDB_ROOT_USERNAME
- NoEcho: false
  Type: String
  AllowedPattern: ''
  Label: MONGO_INITDB_ROOT_PASSWORD
  ConstraintDescription: ''
  Name: MONGO_INITDB_ROOT_PASSWORD
DockerComposeYamlPath: docker-compose.yaml
Owner: JJGGu
Branch: main
Platform: github
